// DESIGN-SHOWCASE — the re-homed HYBRID visual snapshot (SPEC-0033 §6 / DESIGN-9; design-system-showcase.md).
//
// Boots the REAL packaged app and snapshots the static primitive gallery. The whole point of the re-home
// (#233 parked): the gallery is **copilot/pipeline/`active`-free** — it renders on an empty userDataDir
// with NO vault, so there's no git+pipeline harness to set up (that's what sank the feature-surface
// snapshot). Reached via the dev `#showcase` hash (never in the user nav). Two forced `color-scheme`
// snapshots cover the `prefers-color-scheme` light override; `reducedMotion: reduce` zeroes the `busy`
// breathe via the shipped reset so the capture is deterministic (DESIGN-SHOWCASE §4).
//
// CI-only / opt-in (SPEC-0012 TEST-9). The *-linux.png baselines are generated + committed by the
// `snapshots` ci.yml job (`update_snapshots` dispatch, #235) — NOT locally on macOS (a darwin baseline
// would never match the linux CI render). KB-QD owns the snapshot mechanics; this is the wiring.
import { test, expect, _electron as electron, type ElectronApplication } from '@playwright/test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { builtMainEntry } from './packagedApp';

// Per-platform baseline; the gating reference is linux (where the snapshots job runs in CI). Skip on
// macOS/Windows — those runners have no `-darwin`/`-win32` baseline and would fail on a missing ref.
test.describe('DESIGN-SHOWCASE — primitive gallery visual snapshot (WS2 HYBRID guard, re-homed)', () => {
  test.skip(process.platform !== 'linux', 'visual baseline is linux-only (generated by the snapshots ci.yml job)');

  let app: ElectronApplication | null = null;
  let userDataDir: string | null = null;

  test.afterEach(async () => {
    await app?.close();
    app = null;
    if (userDataDir) {
      try {
        fs.rmSync(userDataDir, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
      } catch {
        /* leave it for the OS to reap */
      }
    }
    userDataDir = null;
  });

  test('renders every blessed primitive × variant × state, in both themes — on NO vault (no pipeline/active)', async () => {
    const main = builtMainEntry();
    expect(main, 'built bundle not found — run `npm run package` first').toBeTruthy();
    // A FRESH empty userDataDir → no active vault → the app boots to Setup; we then jump to the dev
    // showcase via the hash. No KB seeding, no git, no pipeline — that's the re-home win.
    userDataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kb-e2e-showcase-'));

    app = await electron.launch({ args: [main as string, `--user-data-dir=${userDataDir}`] });
    const page = await app.firstWindow();
    await page.waitForLoadState('domcontentloaded');

    // Reach the dev gallery: set the hash post-boot (renderer's hashchange → mountShowcase). No IPC.
    // `window` here is the browser global (evaluated in-page), not the Playwright Page.
    await page.evaluate(() => {
      window.location.hash = 'showcase';
    });
    const gallery = page.locator('.showcase');
    await expect(gallery).toBeVisible({ timeout: 15_000 });
    await expect(page.locator('.showcase-section')).toHaveCount(4); // Button · SegmentedControl · ConfirmInline · EditableField

    // Dark (default) — reduced-motion zeroes the busy pulse via the shipped reset → deterministic.
    await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
    await expect(gallery).toHaveScreenshot('showcase-dark.png');

    // Light — exercises the `prefers-color-scheme: light` token override (must stay covered).
    await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'reduce' });
    await expect(gallery).toHaveScreenshot('showcase-light.png');
  });
});
